
name: ci

on:
  workflow_call:

jobs:
  build-1:
    uses: ./.github/workflows/build.yml

  build-2:
    uses: ./.github/workflows/build.yml

  build-3:
    uses: ./.github/workflows/build.yml

  build-4:
    uses: ./.github/workflows/build.yml

  aggregate-builds:
    runs-on: []
    needs: [build-1, build-2, build-3, build-4]

  test-1:
    needs: [aggregate-builds]
    uses: ./.github/workflows/test.yml
  test-2:
    needs: [aggregate-builds]
    uses: ./.github/workflows/test.yml
  test-3:
    needs: [aggregate-builds]
    uses: ./.github/workflows/test.yml
  test-4:
    needs: [aggregate-builds]
    uses: ./.github/workflows/test.yml

  aggregate-tests:
    runs-on: []
    needs: [test-1, test-2, test-3, test-4]
