---
name: Continuous Integration

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build-test-windows:
    runs-on: [ubuntu-latest]
    name: Windows Host Build & Test
    steps:
      - run: echo build-and-test windows

  build-test-linux:
    name: Linux Host Build & Test
    runs-on: [ubuntu-latest]
    steps:
      - run: echo build-and-test linux

  build-embedded:
    name: Embedded Build
    strategy:
      matrix:
        preset: ["device-a", "device-b",]
    runs-on: [ubuntu-latest]
    steps:
      - run: echo embedded-build ${{ matrix.preset }}

  aggregate-build:
    name: Aggregate Build Info
    runs-on: [ubuntu-latest]
    needs: [build-test-windows, build-test-linux, build-embedded]
    steps:
      - run: echo aggregate-build information

  test-device-a:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        test:
          - Smoke
          - Startup
    needs: [aggregate-build]
    uses: ./.github/workflows/test-device.yml
    with:
      testTag: ${{ matrix.test }}
      deviceName: "device-a"
    secrets: inherit

  test-device-b:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        test:
          - Smoke
          - Startup
    needs: [aggregate-build]
    uses: ./.github/workflows/test-device.yml
    with:
      testTag: ${{ matrix.test }}
      deviceName: "device-b"
    secrets: inherit

  test-results:
    strategy:
      fail-fast: false
      matrix:
        device:
          - device-a
          - device-b
    needs:
      - test-device-a
      - test-device-b
    uses: ./.github/workflows/test-results.yml
    with:
      device: ${{ matrix.device }}

  promote-build:
    name: Promote Build to Tested
    runs-on: [ubuntu-latest]
    needs: [test-results]
    steps:
      - run: echo promote-build
