---
name: Continuous Integration

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test-device-a:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        test:
          - Smoke
          - Startup
    uses: ./.github/workflows/test-device.yml
    with:
      testTag: ${{ matrix.test }}
      deviceName: "device-a"
    secrets: inherit

  test-device-b:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        test:
          - Smoke
          - Startup
          - ThisFileDoesNotExist
    uses: ./.github/workflows/test-device.yml
    with:
      testTag: ${{ matrix.test }}
      deviceName: "device-b"
    secrets: inherit

  test-results:
    strategy:
      fail-fast: false
      matrix:
        device:
          - device-a
          - device-b
    needs:
      - test-device-a
      - test-device-b
    uses: ./.github/workflows/test-results.yml
    with:
      device: ${{ matrix.device }}

  promote-build:
    name: Promote Build to Tested
    runs-on: [ubuntu-latest]
    needs: [test-results]
    steps:
      - run: echo promote-build
