---
name: Documentation

on:
  workflow_call:

permissions:
  contents: read

jobs:
  generate-documents:
    name: Generate Documents
    runs-on: [ubuntu-latest]
    steps:
      - run: echo create documentation