---
name: Test device-x

on:
  workflow_call:
    inputs:
      testTag:
        description: Test tag
        required: true
        type: string
      deviceName:
        description: Device name
        required: true
        type: string

permissions:
  contents: read

run-name: testing ${{ inputs.device }} with ${{ inputs.deviceName }}

jobs:
  test-device-x:
    runs-on: [ubuntu-latest]
    name: Test device-x ${{ inputs.deviceName }} | ${{ inputs.testTag }}
    steps:
      - run: echo "tests ${{ inputs.deviceName }} | ${{ inputs.testTag }}"
  
  intermediate-results-x:
    runs-on: [ubuntu-latest]
    needs: [test-device-x]
    name: Result device-x ${{ inputs.deviceName }} | ${{ inputs.testTag }}
    steps:
      - run: echo "results ${{ inputs.deviceName }} | ${{ inputs.testTag }}"
