
name: test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
