---
name: Test device-x

on:
  workflow_call:
    inputs:
      testTag:
        description: Test tag
        required: true
        type: string
      deviceName:
        description: Device name
        required: true
        type: string

permissions:
  contents: read

jobs:
  test-device-x:
    runs-on: [ubuntu-latest]
    name: Test device-x ${{ inputs.deviceName }} | ${{ inputs.testTag }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: echo "tests ${{ inputs.deviceName }} | ${{ inputs.testTag }}"
      - name: Upload junit xmls
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: ${{ inputs.deviceName }}-test-xml
          path: |
            TEST-BLE-${{ inputs.deviceName }}-${{ inputs.testTag }}.xml
          if-no-files-found: error
          retention-days: 5
      - uses: ./.github/actions/evaluate-test-results
        id: test-results
        with:
          token: ${{ github.token }}
          deviceName: TEST-BLE-${{ inputs.deviceName }}-${{ inputs.testTag }}.xml
          testFile: ${{ inputs.deviceName }}
