
# This is a basic workflow to help you get started with Actions

name: workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci:
    uses: ./.github/workflows/ci.yml

  static-analysis:
    uses: ./.github/workflows/static-analysis.yml

  documentation:
    needs: [ci, static-analysis]
    uses: ./.github/workflows/documentation.yml
